### PR TITLE
Disable showing stored procedures until can edit, fixes #457

### LINKED ISSUE #457: Disable showing stored procs until we can view/edit them

### PR DESCRIPTION
**Pull request by StephenWeatherford**

### CODE REVIEW

**Comment by StephenWeatherford** [comment]
@fiveisprime, @jinglouMSFT If I add delete do you feel it's worth shipping with user procs?

**Comment by fiveisprime** [comment]
Yeah, that's fine.

**Comment by StephenWeatherford** [comment]
Closing in favor of https://github.com/Microsoft/vscode-cosmosdb/issues/465

**Comment by StephenWeatherford** [comment]
Re-opening.

**Comment by StephenWeatherford** [comment]
> my only problem with this is that we've inserted a "Documents" node into the tree for no apparent reason. Before, at least I knew you did it to support stored procedures

We'll have to live with this for now.  The counterargument was that some customers may interpret the lack in behavior as a bug or just be annoyed by it.

**Comment by StephenWeatherford** [comment]
Re-re-closing

**Pull request closed without merging**
