### PR TITLE
Update command id

### PR DESCRIPTION
**Pull request by chrmarti**
Small clean up on the account extension's side.

### CODE REVIEW

**Comment by EricJizbaMSFT** [comment]
@chrmarti when will the new account extension be published with this change?

**Comment by chrmarti** [comment]
@EricJizbaMSFT: @chrisdias will coordinate with you to roll this out simultaneously (early next week I believe).

**Comment by EricJizbaMSFT** [comment]
I would actually prefer the account extension be updated ASAP so that we can test on the latest version before our release. We haven't published the Cosmos DB or App Service extensions yet, so there's no worry about breaking anyone (not sure if any other extensions have a dependency)

**Comment by chrisdias** [comment]
Good point about not breaking anyone, we will do this today.

**Comment by chrisdias** [comment]
@ericjizbamsft we've published a new version of azure account to the marketplace.

**Pull request merged**
